### ISSUE TITLE
Fatal error when using the Import Data Sheet function

### ISSUE THREAD

**Issue by emmaherrod** [cwarwicker/moodle-block_gradetracker#13]
Following error generated when uploading grades using "Import Data Sheet" tool:

Fatal error: Call to a member function getAwardByShortName() on boolean in /var/www/moodle/blocks/gradetracker/classes/qualification/UserQualification.class.php on line 2074

**Comment by cwarwicker** [comment]
Hi,

Is this student grid, unit grid or class grid? And can you email me a copy of the sheet you are trying to import, as well as a freshly exported one, so i can see if there are any differences causing the problem?

**Comment by cwarwicker** [comment]
Hi,

Is this student grid, unit grid or class grid? And can you email me a copy of the sheet you are trying to import, as well as a freshly exported one, so i can see if there are any differences causing the problem?


Regards,

Conn

 
 

Sent: Friday, November 03, 2017 at 9:07 PM

**Comment by emmaherrod** [comment]
Thanks Conn - this is for the CLASS GRID. I will email you the files as requested.
