### ISSUE TITLE
Import Data Sheet produces 500 error using class/user/unit grids

### ISSUE THREAD

**Issue by stevenlovidge** [cwarwicker/moodle-block_gradetracker#26]
Import Data Sheet produces 500 error using class/user/unit grids.
Export works fine!
PHP error is 'Fatal error: Class 'PHPExcel_Shared_OLERead' not found in C:\inetpub\wwwroot\moodledev\lib\phpexcel\PHPExcel\Reader\Excel5.php on line 438'
Suspect it should be using excel2007 class?

**Comment by cwarwicker** [comment]
[44 Testing  BTEC Level 3 Diploma  testing.xlsx](https://github.com/cwarwicker/moodle-block_gradetracker/files/3397358/44.Testing.BTEC.Level.3.Diploma.testing.xlsx)

Example of a unit grid export from their site which doesn't work.

**Comment by cwarwicker** [comment]
Still unable to replicate, even using file from their moodle.

Hopefully a moodle upgrade will fix whatever the issue in their phpexcel library is.
