### ISSUE TITLE
issue with bc_dashboard 

### ISSUE THREAD

**Issue by frankcurley** [cwarwicker/moodle-block_gradetracker#6]
Hi Github
I am trying to get the Bedford Grade Tracker installed on Moodle 3.3issue and got this response from the company setting it up. Hope someone here can help.

Testing the bc_dashboard block. When we try to create our own SQL report running a SELECT statement and save the report, we get the error in the attached file (bc_block.txt).

If you're able to contact the plugin developers to see if this is a known error, or if we are simply doing something wrong that would be great. It would also be good for us to know if there are restrictions in place on what types of database queries can be run by the user.

If you could also ask them to confirm the bc_dashboard and gradetracker plugins are compatible with Moodle 3.3 that would also be great.

**Comment by cwarwicker** [comment]
Hi, sorry for the late reply, I didn't have my email notifications setup properly. I can't see an attached text file, but I'm guessing it was something about the "params" field being null? If so, I'm fixing that today and will push up the changes soon. If not, can you let me know what the error was?

**Comment by cwarwicker** [comment]
And yes, it should be compatible with 3.3.
